import { FlowDef } from './types';

/**
 * Default flow: Patriot Claims / Allstate wind-hail protocol.
 * Source of truth: docs/source/default-flow-spec.md (distilled from Patriot
 * Certified Inspector course transcripts). Labels follow ALDD:
 * Area, Location, Description, Detail — measurements & condition adjectives
 * are appended by the inspector in the caption editor.
 */
export const patriotAllstateFlow: FlowDef = {
  id: 'patriot-allstate-wind-hail',
  carrier: 'Allstate (Patriot Claims protocol)',
  name: 'Wind / Hail Inspection',
  description:
    'Default Patriot Claims vendor photo appointment & ladder assist protocol for Allstate wind-hail claims.',
  sections: [
    {
      id: 'arrival',
      area: 'start',
      skippable: false,
      title: 'Arrival & Setup',
      icon: '1',
      subtitle: 'Branding, vehicle, address verification',
      prompts: [
        { id: 'branding', label: 'Patriot Branding', hint: 'Selfie with branded apparel visible' },
        { id: 'vehicle', label: 'Inspection Vehicle' },
        { id: 'front-of-house', label: 'Front of House', hint: 'Full overview — becomes the report cover photo' },
        { id: 'risk-address', label: 'Risk Address', hint: 'House number close-up — verify address before anything else' },
        { id: 'cougar-paws', label: 'Cougar Paws at Roof Access Point', hint: 'Mandatory on every roof inspection — compliance + vendor-damage protection' },
      ],
      questions: [
        { id: 'insuredPresent', text: 'Was the named insured present?', type: 'yesno', group: 'General' },
        { id: 'whoOnRoof', text: 'Who was on the roof at time of inspection?', type: 'choice', multi: true, choices: ['Patriot Rep', 'Outside Adjuster', 'Contractor', 'Other'], group: 'General' },
        { id: 'frontDirection', text: 'Front of house faces which direction?', type: 'choice', choices: ['North', 'Northeast', 'East', 'Southeast', 'South', 'Southwest', 'West', 'Northwest'], group: 'General' },
      ],
    },
    {
      id: 'elevations',
      area: 'elevations',
      title: 'Lower Elevations',
      icon: '2',
      subtitle: 'Siding, vents, collateral — F/L/B/R',
      repeat: { noun: 'Elevation', presets: ['Front', 'Left', 'Back', 'Right'], addable: true },
      prompts: [
        { id: 'elev-overview', label: '{instance} Elevation Overview', hint: 'Add calculated/AR SqFt to caption when siding is affected' },
        { id: 'siding-id', label: '{instance} Elevation Siding Type & Exposure', hint: 'Tape measure visible on exposure. Aluminum: metal gauge (.019/.024). Hardboard/fiber cement: 6/8/12 in.' },
        { id: 'siding-damage', label: '{instance} Elevation Siding Potential Damage', hint: 'Vinyl: bottom lip & midline cracks. Aluminum: flash for shadowing. Include SqFt math in caption.', optional: true },
        { id: 'windows', label: '{instance} Elevation Window', hint: 'Screens, glazing/glass, beading, wraps — chalk + close-ups with measurements. Record count and sizes (negative space, e.g. 2 @ 6x5).', optional: true },
        { id: 'doors', label: '{instance} Elevation Door', hint: 'Door faces, wraps, weather stripping — dents/spatter close-ups. Record sizes for negative space (e.g. 3x7).', optional: true },
        { id: 'house-wrap', label: '{instance} Elevation House Wrap Exposed', optional: true },
        { id: 'foam-insulation', label: '{instance} Elevation Foam Insulation Exposed', hint: '3/4" rigid foam under siding', optional: true },
        { id: 'painted-trim', label: '{instance} Elevation Painted Trim', hint: 'Measure all linear feet; count windows with painted trim', optional: true },
        { id: 'dryer-vent', label: '{instance} Elevation Dryer Vent', hint: 'Close-up of dents/cracks/broken flappers', optional: true },
        { id: 'gable-vent', label: '{instance} Elevation Gable Vent', hint: 'Context + detail photo; material (vinyl/metal/wood); painted?', optional: true },
        { id: 'light-blocks', label: '{instance} Elevation Light/Outlet Block', hint: 'Count them — mounted through siding', optional: true },
        { id: 'collateral', label: '{instance} Elevation Potential Collateral', hint: 'Electric panel, gas meter, AC fins, cable box — EVERY elevation, even if clean. Caption: item + clean | spatter present + size', optional: true },
        { id: 'cornice-returns', label: '{instance} Elevation Cornice Return', hint: 'At roof-to-wall connection; counts entered in roof section only if that slope has findings', optional: true },
        { id: 'gutters', label: '{instance} Elevation Gutter', hint: 'Topside + face; size, painted, material; chalk when calling a condition', optional: true },
        { id: 'downspouts', label: '{instance} Elevation Downspout', hint: 'Full run + close-ups of dents/spatter; note size (2x3 / 3x4), material, painted in caption', optional: true },
      ],
      instanceQuestions: [
        { id: 'windowCount', text: 'Windows on this elevation (count)', type: 'number', autoFromPrompt: 'windows', promptId: 'windows' },
        { id: 'windowSizes', text: 'Window sizes (e.g. 2 @ 6x5)', type: 'text', promptId: 'windows' },
        { id: 'windowsDamaged', text: 'Windows potentially damaged (of total — screens/glazing/wraps)', type: 'text', promptId: 'windows' },
        { id: 'doorCount', text: 'Doors on this elevation (count)', type: 'number', autoFromPrompt: 'doors', promptId: 'doors' },
        { id: 'doorSizes', text: 'Door sizes (e.g. 1 @ 3x7)', type: 'text', promptId: 'doors' },
        { id: 'doorsDamaged', text: 'Doors potentially damaged (of total)', type: 'text', promptId: 'doors' },
        { id: 'negativeSpaceSqFt', text: 'Negative space total SqFt (windows + doors)', type: 'number', unit: 'SqFt', promptId: 'windows' },
        { id: 'sidingType', text: 'Siding type', type: 'choice', choices: ['Vinyl', 'Aluminum', 'Steel', 'Seamless Steel', 'T1-11', 'Hardboard', 'Fiber Cement', 'Stucco', 'Brick', 'Other'], promptId: 'siding-id' },
        { id: 'exposure', text: 'Exposure / thickness', type: 'text', promptId: 'siding-id' },
        { id: 'totalSidingSqFt', text: 'Total siding SqFt (net of windows/doors)', type: 'number', unit: 'SqFt', promptId: 'siding-id' },
        { id: 'replaceSqFt', text: 'Potentially replace SqFt', type: 'number', unit: 'SqFt', promptId: 'siding-damage' },
        { id: 'paintedTrimLF', text: 'Painted trim (linear ft)', type: 'number', unit: 'linear ft', promptId: 'painted-trim' },
        { id: 'paintedWindowCount', text: 'Windows with painted trim', type: 'number', promptId: 'painted-trim' },
        { id: 'dryerVents', text: 'Dryer vents (damaged of total, e.g. 1 of 2)', type: 'text', promptId: 'dryer-vent' },
        { id: 'gableVents', text: 'Gable vents (damaged of total + material)', type: 'text', promptId: 'gable-vent' },
        { id: 'lightBlocks', text: 'Light/outlet blocks (count)', type: 'number', autoFromPrompt: 'light-blocks', promptId: 'light-blocks' },
        { id: 'gutters', text: 'Gutters (damaged of total, size, paint, material)', type: 'text', promptId: 'gutters' },
        { id: 'downspoutsDamaged', text: 'Downspouts potentially damaged (of total, e.g. 1 of 2)', type: 'text', promptId: 'downspouts' },
        { id: 'downspoutSize', text: 'Downspout size (width x depth)', type: 'choice', choices: ['2\u2033 x 3\u2033', '3\u2033 x 4\u2033', '3\u2033 Round', '4\u2033 Round', 'Other'], promptId: 'downspouts' },
        { id: 'downspoutMaterial', text: 'Downspout material', type: 'choice', choices: ['Aluminum', 'Steel', 'Copper', 'Vinyl', 'Other'], promptId: 'downspouts' },
        { id: 'downspoutPainted', text: 'Downspouts painted?', type: 'yesno', promptId: 'downspouts' },
        { id: 'downspoutLF', text: 'Downspout total length on this elevation (linear ft)', type: 'number', unit: 'linear ft', promptId: 'downspouts' },
      ],
    },
    {
      id: 'roof-eave',
      area: 'roof',
      title: 'Roof Eave',
      icon: '3',
      subtitle: 'From the ladder, before stepping on',
      prompts: [
        { id: 'eave-overhang', label: 'Eave Overhang Measurement', hint: 'Tape visible: siding/frieze board to fascia — exclude the gutter' },
        { id: 'shingle-gauge', label: 'Shingle Gauge', hint: 'Field shingle if eave won’t lift safely; never hip/ridge shingles' },
        { id: 'pitch-gauge', label: 'Pitch', hint: 'Caption: Pitch - N/12. Extra photo if any slope ≥ 10/12 (billing)' },
        { id: 'layer-view', label: 'Layer View', hint: 'Flash ON. Single layer w/ starter vs additional layers' },
        { id: 'underlayment', label: 'Underlayment', hint: 'Synthetic felt / 15lb / 30lb / peel & stick — note in caption' },
        { id: 'drip-edge', label: 'Drip Edge', hint: 'Eave AND rake — one corner angle can show both. Painted? Gutter apron vs drip edge', optional: true },
        { id: 'gutter-topside', label: 'Topside Gutter (chalked)', hint: 'Rub chalk on top lip: potential hail | no potential hail', optional: true },
        { id: 'gutter-protection', label: 'Gutter Protection', hint: 'Average / High / Premium (Leaf Guard, Gutter Helmet = premium)', optional: true },
      ],
      questions: [
        { id: 'eaveDepth', text: 'Eave depth (inches)', type: 'number', unit: 'in', group: 'Roof Components', promptId: 'eave-overhang' },
        { id: 'iceWaterShield', text: 'Ice & water shield present?', type: 'yesno', group: 'Roof Components', promptId: 'eave-overhang' },
        { id: 'predomPitch', text: 'Predominant pitch (N/12)', type: 'text', group: 'Roof Components', promptId: 'pitch-gauge' },
        { id: 'layers', text: 'Layers', type: 'choice', choices: ['Single Layer w/Starter', '2 Layers', '3+ Layers'], group: 'Roof Components', promptId: 'layer-view' },
        { id: 'layerType', text: 'Additional layer type', type: 'choice', choices: ['N/A', 'Composition', 'Wood Shake'], group: 'Roof Components', promptId: 'layer-view' },
        { id: 'underlaymentType', text: 'Underlayment (felt type)', type: 'choice', choices: ['Synthetic Felt', '15 lb Felt', '30 lb Felt', 'Peel & Stick', 'Unknown'], group: 'Roof Components', promptId: 'underlayment' },
        { id: 'dripEdgeMaterial', text: 'Drip edge material', type: 'choice', choices: ['Aluminum', 'Steel', 'None'], group: 'Roof Components', promptId: 'drip-edge' },
        { id: 'dripEdgePainted', text: 'Drip edge painted?', type: 'yesno', group: 'Roof Components', promptId: 'drip-edge' },
        { id: 'dripEdgeLocations', text: 'Drip edge locations', type: 'choice', choices: ['Eave', 'Rake', 'Eave + Rake'], group: 'Roof Components', promptId: 'drip-edge' },
        { id: 'gutterThroughDrip', text: 'Gutter installed through drip edge?', type: 'yesno', group: 'Roof Components', promptId: 'gutter-topside' },
        { id: 'edgeType', text: 'Edge metal type (short kick-out = drip edge; long leg into gutter = gutter apron)', type: 'choice', choices: ['Drip Edge', 'Gutter Apron', 'Both', 'None'], group: 'Roof Components', promptId: 'drip-edge' },
        { id: 'gutterProtection', text: 'Gutter protection grade (Leaf Guard/Gutter Helmet = Premium)', type: 'choice', choices: ['None', 'Average', 'High', 'Premium'], group: 'Roof Components', promptId: 'gutter-protection' },
      ],
    },
    {
      id: 'roof-overview',
      area: 'roof',
      title: 'Roof Overview & Components',
      icon: '4',
      subtitle: '360s, valleys, ridge, ventilation',
      prompts: [
        { id: '360-front', label: '360 Overview - Front', hint: 'From highest central point' },
        { id: '360-left', label: '360 Overview - Left' },
        { id: '360-back', label: '360 Overview - Back' },
        { id: '360-right', label: '360 Overview - Right' },
        { id: 'valley', label: 'Valley Material', hint: 'Chalk open metal; label intersecting facets; note which slope lays on top' },
        { id: 'hip-ridge', label: 'Hip & Ridge Condition', hint: 'Angled shot showing profile thickness — plane landing, not helicopter' },
        { id: 'ridge-vent', label: 'Ridge Vent + Measurement', hint: 'Required on EVERY inspection, damage or not — measure every run in linear ft; chalk aluminum. Skip only if no ridge vent exists.', optional: true },
        { id: 'chimney', label: 'Chimney — Cap, Chase Cover, Flashing', hint: 'Flashing size: small/medium/large; facet letter in caption; use sun/shadow for flue caps', optional: true },
        { id: 'skylights', label: 'Skylight & Flashing', hint: 'Head, apron, step flashing + cladding; facet letter in caption', optional: true },
        { id: 'flashing', label: 'Step / Transition Flashing', hint: 'Dormers, sidewalls, pitch changes — chalk when safe, linear ft in captions (step or 14\u2033 transition)', optional: true },
        { id: 'decking', label: 'Roof Decking Condition', hint: 'Light test steps; rafter-walk if spongy. Wood rot = deferred maintenance, penetrations = storm. Estimate affected SqFt in caption.', optional: true },
        { id: 'flat-roof', label: 'Flat Roof — Overview + Material ID', hint: 'Overviews all 4 directions from center; material in caption (TPO/EPDM/Mod Bit); 6+ condition photos; overlaps; every penetration; correlate interior stains', optional: true },
        { id: 'component-count', label: 'Component Count Chalk Board', hint: 'F/L/B/R columns; PJ EV BV RV TV PV abbreviations; small p = painted', optional: true },
        { id: 'satellite', label: 'Satellite / Antenna / Solar', hint: 'Spatter check; solar: affected of total + manufacturer labels', optional: true },
      ],
      questions: [
        { id: 'roofType', text: 'Roof type', type: 'choice', choices: ['Gable (5% waste)', 'Hip (10% waste)', 'Combination'], group: 'Roof Data' },
        { id: 'mainMaterial', text: 'Main roof material / type', type: 'choice', choices: ['3-Tab 20yr', '3-Tab 25yr', 'T-Lock', 'Laminate 30yr (avg)', 'Laminate 35-40yr (high)', 'Laminate 50yr (premium)', 'Impact Resistant', 'Wood Shake', 'Metal', 'Tile', 'Synthetic', 'Stone-Coated Steel', 'Flat'], group: 'Roof Data' },
        { id: 'roofAge', text: 'Estimated roof age (ask homeowner first)', type: 'text', group: 'Roof Data' },
        { id: 'stories', text: 'Stories', type: 'choice', choices: ['1', '1.5', '2', '2+'], group: 'Roof Data' },
        { id: 'ridgeMaterial', text: 'Ridge', type: 'choice', choices: ['Standard Asphalt', 'High Profile', 'Metal', 'Other'], group: 'Roof Data', promptId: 'hip-ridge' },
        { id: 'hipMaterial', text: 'Hips', type: 'choice', choices: ['N/A', 'Standard Asphalt', 'High Profile', 'Metal', 'Other'], group: 'Roof Data', promptId: 'hip-ridge' },
        { id: 'valleyType', text: 'Valley', type: 'choice', choices: ['N/A', 'Closed', 'Closed w/ Valley Metal', 'Open 24" Flashing', 'Open W-Style', 'Woven'], group: 'Roof Data', promptId: 'valley' },
        { id: 'ridgeVentLF', text: 'Ridge vent total (linear ft)', type: 'number', unit: 'linear ft', group: 'Roof Data', promptId: 'ridge-vent' },
        { id: 'aerialMeasurements', text: 'Aerial measurements available?', type: 'yesno', group: 'Roof Data' },
        { id: 'deckingType', text: 'Decking type', type: 'choice', choices: ['Not visible', '1/2\u2033 OSB', '1/2\u2033 CDX Plywood', '1x6 Tongue & Groove', '1x6 Spaced/Skip'], group: 'Roof Data', promptId: 'decking' },
        { id: 'deckingAffectedSqFt', text: 'Decking affected SqFt (storm or rot — say which in notes)', type: 'number', unit: 'SqFt', group: 'Roof Data', promptId: 'decking' },
      ],
    },
    {
      id: 'test-squares',
      area: 'roof',
      quadrants: {
        sizeQuestionId: 'tsSize',
        afterPromptId: 'ts-overview',
        counts: { '10x10': 6, '10x5': 3, '5x5': 0 },
        defaultSize: '10x10',
      },
      title: 'Slopes & Test Squares',
      icon: '5',
      subtitle: 'Test square, conditions, vents — per slope',
      repeat: { noun: 'Slope', presets: ['Front', 'Left', 'Back', 'Right'], addable: true },
      prompts: [
        { id: 'ts-label', label: '{instance} Slope Test Square Label', hint: 'Chalk header: slope/compass + size, e.g. F/N 10x10' },
        { id: 'ts-overview', label: '{instance} Slope Test Square Overview', hint: 'From below looking up-slope, whole square in frame, size in caption' },
        { id: 'pipe-jacks', label: '{instance} Slope Pipe Jack', hint: 'Plastic / split boot / lead — chalk soft metals; painted? Close-up per example.', optional: true },
        { id: 'box-vents', label: '{instance} Slope Box/Turtle Vent', hint: 'Galvanized or aluminum: chalk. Plastic: no chalk needed. Painted goes in caption.', optional: true },
        { id: 'power-vents', label: '{instance} Slope Power Vent', hint: 'Mushroom caps near the ridge, thermostat-driven; metal or plastic; painted?', optional: true },
        { id: 'furnace-vents', label: '{instance} Slope Furnace Vent', hint: 'Center-roof, high-temp combustion. Size 5/6/8\u2033 — measure the PIPE, never the cap.', optional: true },
        { id: 'exhaust-caps', label: '{instance} Slope Exhaust Cap', hint: 'Bath/kitchen/dryer exhaust — near edges, low temp. Measure the pipe stack; painted?', optional: true },
        { id: 'rain-diverters', label: '{instance} Slope Rain Diverter', hint: 'Above doors/walkways/AC — LxW in caption.', optional: true },
        { id: 'contractor-markings', label: '{instance} Slope Contractor Marking', hint: 'Use different color chalk than theirs. Caption: contractor marking + your read in parentheses, e.g. (potential blister). Only add a hail hit if YOU agree.', optional: true },
      ],
      instanceQuestions: [
        { id: 'tsSize', text: 'Test square size (sets the quadrant prompts and captions)', type: 'choice', choices: ['10x10 (6 sections)', '10x5 (counts ×2)', '5x5 (counts ×4)'], pinned: true },
        { id: 'hailCount', text: 'Potential hail count (upscaled)', type: 'number', group: 'Test Square', promptId: 'ts-overview' },
        { id: 'compass', text: 'Compass direction of slope', type: 'choice', choices: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'], group: 'Test Square', promptId: 'ts-label' },
        { id: 'blisters', text: 'Blisters', type: 'yesno', group: 'Shingle Conditions (this slope)', promptId: 'ts-overview' },
        { id: 'cupCurl', text: 'Cupping / curling', type: 'yesno', group: 'Shingle Conditions (this slope)', promptId: 'ts-overview' },
        { id: 'deckRot', text: 'Deck rot', type: 'yesno', group: 'Shingle Conditions (this slope)', promptId: 'ts-overview' },
        { id: 'granuleLoss', text: 'Granule loss', type: 'yesno', group: 'Shingle Conditions (this slope)', promptId: 'ts-overview' },
        { id: 'mfrDefects', text: 'Manufacturer defects', type: 'yesno', group: 'Shingle Conditions (this slope)', promptId: 'ts-overview' },
        { id: 'mechanical', text: 'Mechanical damage', type: 'yesno', group: 'Shingle Conditions (this slope)', promptId: 'ts-overview' },
        { id: 'nailPops', text: 'Nail pops', type: 'yesno', group: 'Shingle Conditions (this slope)', promptId: 'ts-overview' },
        { id: 'priorRepairs', text: 'Prior repairs', type: 'yesno', group: 'Shingle Conditions (this slope)', promptId: 'ts-overview' },
        { id: 'thermalCracking', text: 'Thermal cracking', type: 'yesno', group: 'Shingle Conditions (this slope)', promptId: 'ts-overview' },
        { id: 'otherFindings', text: 'Other findings notes', type: 'text', group: 'Test Square', promptId: 'ts-overview' },
        { id: 'turbines', text: 'Turbine vents (damaged of total, material, p)', type: 'text' , group: 'Components (this slope)' },
        { id: 'pipeJacksTotal', text: 'Pipe jacks — total', type: 'number', group: 'Components (this slope)', autoFromPrompt: 'pipe-jacks', promptId: 'pipe-jacks' },
        { id: 'pipeJacksDamaged', text: 'Pipe jacks — potentially damaged', type: 'number', group: 'Components (this slope)', promptId: 'pipe-jacks' },
        { id: 'boxVentsTotal', text: 'Box/turtle vents — total', type: 'number', group: 'Components (this slope)', autoFromPrompt: 'box-vents', promptId: 'box-vents' },
        { id: 'boxVentsDamaged', text: 'Box/turtle vents — potentially damaged', type: 'number', group: 'Components (this slope)', promptId: 'box-vents' },
        { id: 'turbinesTotal', text: 'Turbine vents — total', type: 'number', group: 'Components (this slope)', autoFromPrompt: 'turbines', promptId: 'turbines' },
        { id: 'turbinesDamaged', text: 'Turbine vents — potentially damaged', type: 'number', group: 'Components (this slope)', promptId: 'turbines' },
        { id: 'powerVentsTotal', text: 'Power vents — total', type: 'number', group: 'Components (this slope)', autoFromPrompt: 'power-vents', promptId: 'power-vents' },
        { id: 'powerVentsDamaged', text: 'Power vents — potentially damaged', type: 'number', group: 'Components (this slope)', promptId: 'power-vents' },
        { id: 'furnaceVentsTotal', text: 'Furnace vents — total (size in captions)', type: 'number', group: 'Components (this slope)', autoFromPrompt: 'furnace-vents', promptId: 'furnace-vents' },
        { id: 'furnaceVentsDamaged', text: 'Furnace vents — potentially damaged', type: 'number', group: 'Components (this slope)', promptId: 'furnace-vents' },
        { id: 'exhaustCapsTotal', text: 'Exhaust caps — total', type: 'number', group: 'Components (this slope)', autoFromPrompt: 'exhaust-caps', promptId: 'exhaust-caps' },
        { id: 'exhaustCapsDamaged', text: 'Exhaust caps — potentially damaged', type: 'number', group: 'Components (this slope)', promptId: 'exhaust-caps' },
        { id: 'rainDivertersTotal', text: 'Rain diverters — total', type: 'number', group: 'Components (this slope)', autoFromPrompt: 'rain-diverters', promptId: 'rain-diverters' },
        { id: 'rainDivertersDamaged', text: 'Rain diverters — potentially damaged', type: 'number', group: 'Components (this slope)', promptId: 'rain-diverters' },
        { id: 'corniceReturns', text: 'Cornice returns on this slope (count ONLY if slope has findings)', type: 'number', group: 'Components (this slope)' },
      ],
    },
    {
      id: 'wind',
      area: 'roof',
      title: 'Potential Wind & Tree Impact',
      icon: '6',
      subtitle: 'Per directional slope · tap the facet letter',
      repeat: { noun: 'Slope', presets: ['Front', 'Left', 'Back', 'Right'], addable: true },
      prompts: [
        { id: 'wind-overview', label: '{instance} Slope Potential Wind Overview', hint: 'Tap the facet letter (A–F) to label it; include the total potential wind count for this facet in the caption' },
        { id: 'wind-detail', label: '{instance} Slope Potential Wind Detail', hint: 'Tap the facet letter. Chalk strike through shingle face — no circles/arrows. Creased, broken, missing, lifted. Zippering is NOT counted by Allstate — document as contractor consideration only.' },
        { id: 'wind-hip-ridge', label: '{instance} Slope Hip/Ridge Wind (Linear Ft)', hint: 'Linear feet, NOT tab counts; note the two intersecting facet letters', optional: true },
        { id: 'tree-impact', label: '{instance} Slope Tree Impact', hint: 'Tap the facet letter. Safety first — obstruction must be removed; count affected shingles', optional: true },
        { id: 'cad-markup', label: '{instance} Slope CAD Markup Screenshot', hint: 'X per finding + total per facet; upload to documents, never write counts on roof', optional: true },
      ],
      instanceQuestions: [
        { id: 'windCount', text: 'Potential wind count (this slope)', type: 'number', promptId: 'wind-overview' },
        { id: 'facetLetters', text: 'Facet letters on this slope (e.g. A, B)', type: 'text', promptId: 'wind-overview' },
        { id: 'twoPlusStories', text: 'Slope is 2+ stories?', type: 'yesno' },
        { id: 'treeCount', text: 'Tree-impact shingle count', type: 'number', promptId: 'tree-impact' },
      ],
    },
    {
      id: 'interior',
      area: 'inside',
      title: 'Interior Rooms',
      icon: '7',
      subtitle: 'Per-room findings (when in scope)',
      repeat: { noun: 'Room', addable: true },
      prompts: [
        { id: 'room-overview', label: '{instance} Overview', hint: 'Include room dimensions in caption, e.g. (8x12)' },
        { id: 'room-damage', label: '{instance} Potential Damage', hint: 'Close-up with measurement in caption, e.g. potential leak (3x1) on wall', optional: true },
      ],
      instanceQuestions: [
        { id: 'ceilingHeight', text: 'Ceiling height', type: 'text' },
        { id: 'ttlCeilingSqFt', text: 'Total ceiling SqFt', type: 'number', unit: 'SqFt' },
        { id: 'ttlWallSqFt', text: 'Total wall SqFt', type: 'number', unit: 'SqFt' },
        { id: 'affCeilingSqFt', text: 'Affected ceiling SqFt', type: 'number', unit: 'SqFt' },
        { id: 'affWallSqFt', text: 'Affected wall SqFt', type: 'number', unit: 'SqFt' },
        { id: 'perimeter', text: 'Perimeter length', type: 'text' },
        { id: 'baseboards', text: 'Baseboards', type: 'yesno' },
        { id: 'crownMolding', text: 'Crown molding', type: 'yesno' },
        { id: 'ceilingFans', text: 'Ceiling fans', type: 'number' },
        { id: 'ventCount', text: 'Vent count', type: 'number' },
        { id: 'lightCount', text: 'Light count', type: 'number' },
        { id: 'windowCount', text: 'Window count', type: 'number' },
        { id: 'smokeDetector', text: 'Smoke detector', type: 'yesno' },
        { id: 'wallTexture', text: 'Wall texture', type: 'choice', choices: ['Smooth', 'Knockdown', 'Orange Peel', 'Popcorn', 'Other'] },
        { id: 'ceilingTexture', text: 'Ceiling texture', type: 'choice', choices: ['Smooth', 'Knockdown', 'Orange Peel', 'Popcorn', 'Other'] },
        { id: 'roomNotes', text: 'Room notes', type: 'multilineText' },
      ],
    },
    {
      id: 'wrapup',
      area: 'wrapup',
      title: 'Questions & Wrap-Up',
      icon: '8',
      subtitle: 'General, conditions, subrogation, tarps',
      prompts: [
        { id: 'tarp-before', label: 'Tarp - Before Detach', hint: 'Required when a tarp is present', optional: true },
        { id: 'tarp-under', label: 'Tarp - Condition Underneath', optional: true },
        { id: 'tarp-after', label: 'Tarp - After Reset', hint: 'Caption: facet, tarp LxW, cap nail count, shingles affected', optional: true },
        { id: 'prior-repairs', label: 'Prior Repair', hint: 'Overview + close-ups; distribution by slope (counts NOT entered in Inspect)', optional: true },
        { id: 'sketch-ar', label: 'Sketch AR / Diagram Screenshot', hint: 'AR summary + each wall + negative spaces with dimensions', optional: true },
      ],
      questions: [
        { id: 'gotOnRoof', text: 'Did you get on the roof?', type: 'yesno', group: 'General Inspection Questions' },
        { id: 'potentialDamage', text: 'Did the roof have potential hail or wind damage?', type: 'yesno', group: 'General Inspection Questions' },
        { id: 'collateralConsistent', text: 'Is potential collateral damage consistent with report?', type: 'yesno', group: 'General Inspection Questions' },
        { id: 'subroNailSize', text: 'Improper nail/staple size', type: 'yesno', group: 'Subrogation Opportunities' },
        { id: 'subroNailLine', text: 'Nail/staple not on nail line', type: 'yesno', group: 'Subrogation Opportunities' },
        { id: 'subroFasteners', text: 'Improper fasteners installed', type: 'yesno', group: 'Subrogation Opportunities' },
        { id: 'subroExposure', text: 'Improper shingle exposure', type: 'yesno', group: 'Subrogation Opportunities' },
        { id: 'subroMfrDefects', text: 'Manufacturer defects', type: 'yesno', group: 'Subrogation Opportunities' },
        { id: 'matchingAgeRange', text: 'Roof age range (matching states)', type: 'text', group: 'Matching States' },
        { id: 'matchingUniform', text: 'Facets uniform in appearance prior to loss?', type: 'yesno', group: 'Matching States' },
        { id: 'inspectorSummary', text: 'Inspector summary', type: 'multilineText', group: 'Narrative' },
        { id: 'lowerElevationsNote', text: 'Lower elevations narrative', type: 'multilineText', group: 'Narrative' },
        { id: 'roofNote', text: 'Roof narrative', type: 'multilineText', group: 'Narrative' },
      ],
    },
  ],
};
