import { FlowDef } from './types';

/**
 * Default flow: Patriot Claims / Allstate wind-hail protocol.
 * Source of truth: docs/source/default-flow-spec.md (distilled from Patriot
 * Certified Inspector course transcripts). Labels follow ALDD:
 * Area, Location, Description, Detail — measurements & condition adjectives
 * are appended by the inspector in the caption editor.
 */
export const patriotAllstateFlow: FlowDef = {
  id: 'patriot-allstate-wind-hail',
  carrier: 'Allstate (Patriot Claims protocol)',
  name: 'Wind / Hail Inspection',
  description:
    'Default Patriot Claims vendor photo appointment & ladder assist protocol for Allstate wind-hail claims.',
  sections: [
    {
      id: 'arrival',
      title: 'Arrival & Setup',
      icon: '🚚',
      subtitle: 'Branding, vehicle, address verification',
      prompts: [
        { id: 'branding', label: 'Patriot Branding', hint: 'Selfie with branded apparel visible' },
        { id: 'vehicle', label: 'Inspection Vehicle' },
        { id: 'front-of-house', label: 'Front of House', hint: 'Full overview — becomes the report cover photo' },
        { id: 'risk-address', label: 'Risk Address', hint: 'House number close-up — verify address before anything else' },
        { id: 'cougar-paws', label: 'Cougar Paws at Roof Access Point', hint: 'Compliance + vendor-damage protection', optional: true },
      ],
      questions: [
        { id: 'insuredPresent', text: 'Was the named insured present?', type: 'yesno', group: 'General' },
        { id: 'whoOnRoof', text: 'Who was on the roof at time of inspection?', type: 'choice', choices: ['Patriot Rep', 'Outside Adjuster', 'Contractor', 'Other'], group: 'General' },
        { id: 'frontDirection', text: 'Front of house faces which direction?', type: 'choice', choices: ['North', 'Northeast', 'East', 'Southeast', 'South', 'Southwest', 'West', 'Northwest'], group: 'General' },
      ],
    },
    {
      id: 'interior',
      title: 'Interior Rooms',
      icon: '🛋️',
      subtitle: 'Per-room findings (when in scope)',
      repeat: { noun: 'Room', addable: true },
      prompts: [
        { id: 'room-overview', label: '{instance} Overview', hint: 'Include room dimensions in caption, e.g. (8x12)' },
        { id: 'room-damage', label: '{instance} Potential Damage', hint: 'Close-up with measurement in caption, e.g. potential leak (3x1) on wall', optional: true },
      ],
      instanceQuestions: [
        { id: 'ceilingHeight', text: 'Ceiling height', type: 'text' },
        { id: 'ttlCeilingSqFt', text: 'Total ceiling SqFt', type: 'number' },
        { id: 'ttlWallSqFt', text: 'Total wall SqFt', type: 'number' },
        { id: 'affCeilingSqFt', text: 'Affected ceiling SqFt', type: 'number' },
        { id: 'affWallSqFt', text: 'Affected wall SqFt', type: 'number' },
        { id: 'perimeter', text: 'Perimeter length', type: 'text' },
        { id: 'baseboards', text: 'Baseboards', type: 'yesno' },
        { id: 'crownMolding', text: 'Crown molding', type: 'yesno' },
        { id: 'ceilingFans', text: 'Ceiling fans', type: 'number' },
        { id: 'ventCount', text: 'Vent count', type: 'number' },
        { id: 'lightCount', text: 'Light count', type: 'number' },
        { id: 'windowCount', text: 'Window count', type: 'number' },
        { id: 'smokeDetector', text: 'Smoke detector', type: 'yesno' },
        { id: 'wallTexture', text: 'Wall texture', type: 'choice', choices: ['Smooth', 'Knockdown', 'Orange Peel', 'Popcorn', 'Other'] },
        { id: 'ceilingTexture', text: 'Ceiling texture', type: 'choice', choices: ['Smooth', 'Knockdown', 'Orange Peel', 'Popcorn', 'Other'] },
        { id: 'roomNotes', text: 'Room notes', type: 'multilineText' },
      ],
    },
    {
      id: 'elevations',
      title: 'Lower Elevations',
      icon: '🏠',
      subtitle: 'Siding, vents, collateral — F/L/B/R',
      repeat: { noun: 'Elevation', presets: ['Front', 'Left', 'Back', 'Right'], addable: true },
      prompts: [
        { id: 'elev-overview', label: '{instance} Elevation Overview', hint: 'Add calculated/AR SqFt to caption when siding is affected' },
        { id: 'siding-id', label: '{instance} Elevation Siding Type & Exposure', hint: 'Tape measure visible on exposure. Aluminum: metal gauge (.019/.024). Hardboard/fiber cement: 6/8/12 in.' },
        { id: 'siding-damage', label: '{instance} Elevation Siding Potential Damage', hint: 'Vinyl: bottom lip & midline cracks. Aluminum: flash for shadowing. Include SqFt math in caption.', optional: true },
        { id: 'house-wrap', label: '{instance} Elevation House Wrap Exposed', optional: true },
        { id: 'foam-insulation', label: '{instance} Elevation Foam Insulation Exposed', hint: '3/4" rigid foam under siding', optional: true },
        { id: 'painted-trim', label: '{instance} Elevation Painted Trim', hint: 'Measure all linear feet; count windows with painted trim', optional: true },
        { id: 'dryer-vent', label: '{instance} Elevation Dryer Vent', hint: 'Close-up of dents/cracks/broken flappers', optional: true },
        { id: 'gable-vent', label: '{instance} Elevation Gable Vent', hint: 'Context + detail photo; material (vinyl/metal/wood); painted?', optional: true },
        { id: 'light-blocks', label: '{instance} Elevation Light/Outlet Blocks', hint: 'Count them — mounted through siding', optional: true },
        { id: 'collateral', label: '{instance} Elevation Collateral', hint: 'Electric panel, gas meter, AC fins, cable box — EVERY elevation, even if clean. Caption: item + clean | spatter present + size', },
        { id: 'cornice-returns', label: '{instance} Elevation Cornice Returns', hint: 'At roof-to-wall connection; counts entered in roof section only if that slope has findings', optional: true },
        { id: 'gutters-downspouts', label: '{instance} Elevation Gutters & Downspouts', hint: 'Size, painted, material', optional: true },
      ],
      instanceQuestions: [
        { id: 'sidingType', text: 'Siding type', type: 'choice', choices: ['Vinyl', 'Aluminum', 'Steel', 'Seamless Steel', 'T1-11', 'Hardboard', 'Fiber Cement', 'Stucco', 'Brick', 'Other'] },
        { id: 'exposure', text: 'Exposure / thickness', type: 'text' },
        { id: 'totalSidingSqFt', text: 'Total siding SqFt (net of windows/doors)', type: 'number' },
        { id: 'replaceSqFt', text: 'Potentially replace SqFt', type: 'number' },
        { id: 'paintedTrimLF', text: 'Painted trim (linear ft)', type: 'number' },
        { id: 'paintedWindowCount', text: 'Windows with painted trim', type: 'number' },
        { id: 'dryerVents', text: 'Dryer vents (damaged of total, e.g. 1 of 2)', type: 'text' },
        { id: 'gableVents', text: 'Gable vents (damaged of total + material)', type: 'text' },
        { id: 'lightBlocks', text: 'Light/outlet blocks (count)', type: 'number' },
        { id: 'gutters', text: 'Gutters (damaged of total, size, paint, material)', type: 'text' },
        { id: 'downspouts', text: 'Downspouts (damaged of total, size, paint, material)', type: 'text' },
      ],
    },
    {
      id: 'roof-eave',
      title: 'Roof Eave',
      icon: '🪜',
      subtitle: 'From the ladder, before stepping on',
      prompts: [
        { id: 'eave-overhang', label: 'Eave Overhang Measurement', hint: 'Tape visible: siding/frieze board to fascia — exclude the gutter' },
        { id: 'shingle-gauge', label: 'Shingle Gauge', hint: 'Field shingle if eave won’t lift safely; never hip/ridge shingles' },
        { id: 'pitch-gauge', label: 'Pitch', hint: 'Caption: Pitch - N/12. Extra photo if any slope ≥ 10/12 (billing)' },
        { id: 'layer-view', label: 'Layer View', hint: 'Flash ON. Single layer w/ starter vs additional layers' },
        { id: 'underlayment', label: 'Underlayment', hint: 'Synthetic felt / 15lb / 30lb / peel & stick — note in caption' },
        { id: 'drip-edge', label: 'Drip Edge', hint: 'Eave AND rake — one corner angle can show both. Painted? Gutter apron vs drip edge', },
        { id: 'gutter-topside', label: 'Topside Gutter (chalked)', hint: 'Rub chalk on top lip: potential hail | no potential hail' },
        { id: 'gutter-protection', label: 'Gutter Protection', hint: 'Average / High / Premium (Leaf Guard, Gutter Helmet = premium)', optional: true },
      ],
      questions: [
        { id: 'eaveDepth', text: 'Eave depth (inches)', type: 'number', group: 'Roof Components' },
        { id: 'iceWaterShield', text: 'Ice & water shield present?', type: 'yesno', group: 'Roof Components' },
        { id: 'predomPitch', text: 'Predominant pitch (N/12)', type: 'text', group: 'Roof Components' },
        { id: 'layers', text: 'Layers', type: 'choice', choices: ['Single Layer w/Starter', '2 Layers', '3+ Layers'], group: 'Roof Components' },
        { id: 'layerType', text: 'Additional layer type', type: 'choice', choices: ['N/A', 'Composition', 'Wood Shake'], group: 'Roof Components' },
        { id: 'underlaymentType', text: 'Underlayment (felt type)', type: 'choice', choices: ['Synthetic Felt', '15 lb Felt', '30 lb Felt', 'Peel & Stick', 'Unknown'], group: 'Roof Components' },
        { id: 'dripEdgeMaterial', text: 'Drip edge material', type: 'choice', choices: ['Aluminum', 'Steel', 'None'], group: 'Roof Components' },
        { id: 'dripEdgePainted', text: 'Drip edge painted?', type: 'yesno', group: 'Roof Components' },
        { id: 'dripEdgeLocations', text: 'Drip edge locations', type: 'choice', choices: ['Eave', 'Rake', 'Eave + Rake'], group: 'Roof Components' },
        { id: 'gutterThroughDrip', text: 'Gutter installed through drip edge?', type: 'yesno', group: 'Roof Components' },
      ],
    },
    {
      id: 'roof-overview',
      title: 'Roof Overview & Components',
      icon: '⛰️',
      subtitle: '360s, valleys, ridge, ventilation',
      prompts: [
        { id: '360-front', label: '360 Overview - Front', hint: 'From highest central point' },
        { id: '360-left', label: '360 Overview - Left' },
        { id: '360-back', label: '360 Overview - Back' },
        { id: '360-right', label: '360 Overview - Right' },
        { id: 'valley', label: 'Valley Material', hint: 'Chalk open metal; label intersecting facets; note which slope lays on top', optional: true },
        { id: 'hip-ridge', label: 'Hip & Ridge Condition', hint: 'Angled shot showing profile thickness — plane landing, not helicopter' },
        { id: 'ridge-vent', label: 'Ridge Vent + Measurement', hint: 'Measure EVERY run in linear ft, even with no damage; chalk aluminum', optional: true },
        { id: 'ventilation', label: 'Ventilation (per slope)', hint: 'Chalk soft metals; caption: type, material, size, painted (p), damaged of total, slope', optional: true },
        { id: 'chimney', label: 'Chimney — Cap, Chase Cover, Flashing', hint: 'Flashing size: small/medium/large; facet letter in caption; use sun/shadow for flue caps', optional: true },
        { id: 'skylights', label: 'Skylights & Flashing', hint: 'Head, apron, step flashing + cladding; facet letter in caption', optional: true },
        { id: 'component-count', label: 'Component Count Chalk Board', hint: 'F/L/B/R columns; PJ EV BV RV TV PV abbreviations; small p = painted', optional: true },
        { id: 'satellite', label: 'Satellite / Antenna / Solar', hint: 'Spatter check; solar: affected of total + manufacturer labels', optional: true },
      ],
      questions: [
        { id: 'roofType', text: 'Roof type', type: 'choice', choices: ['Gable (5% waste)', 'Hip (10% waste)', 'Combination'], group: 'Roof Data' },
        { id: 'mainMaterial', text: 'Main roof material / type', type: 'choice', choices: ['3-Tab 20yr', '3-Tab 25yr', 'T-Lock', 'Laminate 30yr (avg)', 'Laminate 35-40yr (high)', 'Laminate 50yr (premium)', 'Impact Resistant', 'Wood Shake', 'Metal', 'Tile', 'Synthetic', 'Stone-Coated Steel', 'Flat'], group: 'Roof Data' },
        { id: 'roofAge', text: 'Estimated roof age (ask homeowner first)', type: 'text', group: 'Roof Data' },
        { id: 'stories', text: 'Stories', type: 'choice', choices: ['1', '1.5', '2', '2+'], group: 'Roof Data' },
        { id: 'ridgeMaterial', text: 'Ridge', type: 'choice', choices: ['Standard Asphalt', 'High Profile', 'Metal', 'Other'], group: 'Roof Data' },
        { id: 'hipMaterial', text: 'Hips', type: 'choice', choices: ['N/A', 'Standard Asphalt', 'High Profile', 'Metal', 'Other'], group: 'Roof Data' },
        { id: 'valleyType', text: 'Valley', type: 'choice', choices: ['N/A', 'Closed', 'Closed w/ Valley Metal', 'Open 24" Flashing', 'Open W-Style', 'Woven'], group: 'Roof Data' },
        { id: 'ridgeVentLF', text: 'Ridge vent total (linear ft)', type: 'number', group: 'Roof Data' },
        { id: 'aerialMeasurements', text: 'Aerial measurements available?', type: 'yesno', group: 'Roof Data' },
      ],
    },
    {
      id: 'test-squares',
      title: 'Test Squares',
      icon: '📐',
      subtitle: 'Per directional slope — largest size that fits',
      repeat: { noun: 'Slope', presets: ['Front', 'Left', 'Back', 'Right'], addable: true },
      prompts: [
        { id: 'ts-label', label: '{instance} Slope Test Square Label', hint: 'Chalk header: slope/compass + size, e.g. F/N 10x10' },
        { id: 'ts-overview', label: '{instance} Slope Test Square Overview', hint: 'From below looking up-slope, whole square in frame, size in caption' },
        { id: 'ts-q1', label: '{instance} Slope Test Square Q1' },
        { id: 'ts-q2', label: '{instance} Slope Test Square Q2' },
        { id: 'ts-q3', label: '{instance} Slope Test Square Q3', optional: true },
        { id: 'ts-q4', label: '{instance} Slope Test Square Q4', optional: true },
        { id: 'ts-q5', label: '{instance} Slope Test Square Q5', optional: true },
        { id: 'ts-q6', label: '{instance} Slope Test Square Q6', optional: true },
        { id: 'ts-conditions', label: '{instance} Slope Test Square Conditions', hint: 'One shingle exposure per shot, Q# in caption. Underline hail hits — ONE hit per shingle. Never write counts on the roof.', optional: true },
      ],
      instanceQuestions: [
        { id: 'tsSize', text: 'Test square size', type: 'choice', choices: ['10x10 (6 sections)', '10x5 (counts ×2)', '5x5 (counts ×4)'] },
        { id: 'hailCount', text: 'Potential hail count (upscaled)', type: 'number' },
        { id: 'compass', text: 'Compass direction of slope', type: 'choice', choices: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'] },
        { id: 'granuleLoss', text: 'Granule loss present?', type: 'yesno' },
        { id: 'otherFindings', text: 'Other findings (blisters, thermal cracking, mechanical...)', type: 'text' },
      ],
    },
    {
      id: 'wind',
      title: 'Wind & Tree Impact',
      icon: '💨',
      subtitle: 'Per facet, from the CAD',
      repeat: { noun: 'Facet', addable: true },
      prompts: [
        { id: 'wind-overview', label: 'Facet {instance} Potential Wind Overview', hint: 'Include total potential wind count for this facet in the caption' },
        { id: 'wind-detail', label: 'Facet {instance} Potential Wind Detail', hint: 'Chalk strike through shingle face — no circles/arrows. Creased, broken, missing, lifted.' },
        { id: 'wind-hip-ridge', label: 'Facet {instance} Hip/Ridge Wind (Linear Ft)', hint: 'Linear feet, NOT tab counts; note the two intersecting facets', optional: true },
        { id: 'tree-impact', label: 'Facet {instance} Tree Impact', hint: 'Safety first — obstruction must be removed; count affected shingles', optional: true },
        { id: 'cad-markup', label: 'CAD Markup Screenshot', hint: 'X per finding + total per facet; upload to documents, never write counts on roof', optional: true },
      ],
      instanceQuestions: [
        { id: 'windCount', text: 'Potential wind count', type: 'number' },
        { id: 'twoPlusStories', text: 'Facet is 2+ stories?', type: 'yesno' },
        { id: 'treeCount', text: 'Tree-impact shingle count', type: 'number' },
      ],
    },
    {
      id: 'wrapup',
      title: 'Questions & Wrap-Up',
      icon: '📋',
      subtitle: 'General, conditions, subrogation, tarps',
      prompts: [
        { id: 'tarp-before', label: 'Tarp - Before Detach', hint: 'Required when a tarp is present', optional: true },
        { id: 'tarp-under', label: 'Tarp - Condition Underneath', optional: true },
        { id: 'tarp-after', label: 'Tarp - After Reset', hint: 'Caption: facet, tarp LxW, cap nail count, shingles affected', optional: true },
        { id: 'prior-repairs', label: 'Prior Repairs', hint: 'Overview + close-ups; distribution by slope (counts NOT entered in Inspect)', optional: true },
        { id: 'sketch-ar', label: 'Sketch AR / Diagram Screenshots', hint: 'AR summary + each wall + negative spaces with dimensions', optional: true },
      ],
      questions: [
        { id: 'gotOnRoof', text: 'Did you get on the roof?', type: 'yesno', group: 'General Inspection Questions' },
        { id: 'potentialDamage', text: 'Did the roof have potential hail or wind damage?', type: 'yesno', group: 'General Inspection Questions' },
        { id: 'collateralConsistent', text: 'Is potential collateral damage consistent with report?', type: 'yesno', group: 'General Inspection Questions' },
        { id: 'condBlisters', text: 'Blisters (slopes affected: F L B R)', type: 'text', group: 'Roof Conditions' },
        { id: 'condCupCurl', text: 'Cupping / curling', type: 'text', group: 'Roof Conditions' },
        { id: 'condDeckRot', text: 'Deck rot', type: 'text', group: 'Roof Conditions' },
        { id: 'condGranuleLoss', text: 'Granule loss', type: 'text', group: 'Roof Conditions' },
        { id: 'condMfrDefects', text: 'Manufacturer defects', type: 'text', group: 'Roof Conditions' },
        { id: 'condMechanical', text: 'Mechanical', type: 'text', group: 'Roof Conditions' },
        { id: 'condNailPops', text: 'Nail pops', type: 'text', group: 'Roof Conditions' },
        { id: 'condPriorRepairs', text: 'Prior repairs', type: 'text', group: 'Roof Conditions' },
        { id: 'condThermalCracking', text: 'Thermal cracking', type: 'text', group: 'Roof Conditions' },
        { id: 'subroNailSize', text: 'Improper nail/staple size', type: 'yesno', group: 'Subrogation Opportunities' },
        { id: 'subroNailLine', text: 'Nail/staple not on nail line', type: 'yesno', group: 'Subrogation Opportunities' },
        { id: 'subroFasteners', text: 'Improper fasteners installed', type: 'yesno', group: 'Subrogation Opportunities' },
        { id: 'subroExposure', text: 'Improper shingle exposure', type: 'yesno', group: 'Subrogation Opportunities' },
        { id: 'subroMfrDefects', text: 'Manufacturer defects', type: 'yesno', group: 'Subrogation Opportunities' },
        { id: 'matchingAgeRange', text: 'Roof age range (matching states)', type: 'text', group: 'Matching States' },
        { id: 'matchingUniform', text: 'Facets uniform in appearance prior to loss?', type: 'yesno', group: 'Matching States' },
        { id: 'inspectorSummary', text: 'Inspector summary', type: 'multilineText', group: 'Narrative' },
        { id: 'lowerElevationsNote', text: 'Lower elevations narrative', type: 'multilineText', group: 'Narrative' },
        { id: 'roofNote', text: 'Roof narrative', type: 'multilineText', group: 'Narrative' },
      ],
    },
  ],
};
